### ISSUE TITLE
Idiots

### ISSUE THREAD

**Issue by Elara-Discord-Bots** [DPulavarthy/kaeya#1]
A) Leaving an API key for DBL in the actual files. (because yes.. base64 is "encrypted")
B) Leaving the API link for your google shit.

- I suggest to actually learn how to secure your shit.

**Comment by DPulavarthy** [comment]
I know DBL was a bad idea, but I don't recall posting a Google API key anywhere...
The calls to my google sheets are public so anyone can see the data that the website is requesting.

**Comment by Elara-Discord-Bots** [comment]
I'd make [Glitch](https://glitch.com/) API application so you don't have to keep your token in any of the website files. To have an endpoint for your website stats and DBL stats. It's more secure than having your DBL token in the actual files that someone could use and abuse the key.

**Comment by DPulavarthy** [comment]
I've removed the DBL API and link for top.gg, all data is now updated hourly through the Google Sheets data. [f5fa3e6](https://github.com/DPulavarthy/kaeya/commit/f5fa3e68766996c04c2f6b7cbaec6b5376c5c95d)
I just found Google Sheets to be easier and more accessible for me and the devs.
